### ISSUE TITLE
Namespaces with same values

### ISSUE THREAD

**Issue by rico** [fruux/sabre-xml#103]
I have another question about root node attributes. What I need is this:

    <invoice:request xmlns="http://www.forum-datenaustausch.ch/invoice" xmlns:invoice="http://www.forum-datenaustausch.ch/invoice">

So, same value for default and `invoice` namespace.

Obviously, I can't accomplish this using the service `$service->namespaceMap` array, and the  `$writer->writeAttribute` method throws an exception.

Any ideas? Thanks.

**Comment by evert** [comment]
Huh weird! The namespaceMap indeed has a restriction that you can only specify a namespace once. Why would you want to specify it twice? Are there problems with the application that consumes the xml?

Regardless, writeAttribute should work. How are you attempting to specify it?

**Comment by rico** [comment]
Thanks for you answer & sorry it took so long. It looked weird to me as well, so I asked the developer of the consuming application. It turned out, that I can go on with defining the namespace just once. So closing this - and thanks again.
