### ISSUE TITLE
XML namespace always {}

### ISSUE THREAD

**Issue by Zwaen91** [fruux/sabre-xml#108]
I want to read the following XML. I set up the  namespace mapping and already wrote succesfully some files. Now I want to read but every key starts with a {} like {}Date.
```xml
<ns1:Blaa xmlns:ns1="http://www.blabla.de/ext">
    <Date>2013-02-06</Date>
    <Number>0001482699</Number>
    <Items>
       .....
    </Items>
</ns1:Bla>
```

**Comment by evert** [comment]
Hi @Zwaen91 ,

I think your xml is simply incorrect. If you intended `Date` to be in the specified namespace, this is how your document should look like:

```xml
<ns1:Blaa xmlns:ns1="http://www.blabla.de/ext">
    <ns1:Date>2013-02-06</ns1:Date>
    <ns1:Number>0001482699</ns:1Number>
    <ns1:Items>
       .....
    </ns1:Items>
</ns1:Bla>
```

Or if you don't like to repeat `ns1:` everywhere, you can remove the prefix and get the same sabre/xml output:

```xml
<Blaa xmlns="http://www.blabla.de/ext">
    <Date>2013-02-06</Date>
    <Number>0001482699</Number>
    <Items>
       .....
    </Items>
</Bla>
```

**Comment by evert** [comment]
I'm closing this ticket because it's been a while since the last comment.

If this is indeed still an issue, feel free to comment here so we can continue discussing.

**Comment by mcred** [comment]
I'm running into the same issue. I have the following XML (as provided by a third party):

```xml
<?xml version="1.0" ?>
<response>
  <id-number>2972309</id-number>
  <summary-result>
    <key>id.success</key>
    <message>Pass</message>
  </summary-result>
  <results>
    <key>result.match</key>
    <message>ID Located</message> 
  </results>
</response>
```

I'm using the following to parse the XML into an Array where `$response` is equal to the XML above:
```php
$this->xml = new \Sabre\Xml\Service();
$this->xml->elementMap = [
    'response' => 'Sabre\Xml\Deserializer\keyValue',
    'summary-result' => 'Sabre\Xml\Deserializer\keyValue',
    'results' => 'Sabre\Xml\Deserializer\keyValue'
];
$this->xml->parse($response);
```

When I var_dump the output, it has {} in front of every key:
```php
array(3) {
  '{}id-number' =>
  string(7) "2972309"
  '{}summary-result' =>
  array(2) {
    '{}key' =>
    string(10) "id.success"
    '{}message' =>
    string(4) "Pass"
  }
  '{}results' =>
  array(2) {
    '{}key' =>
    string(12) "result.match"
    '{}message' =>
    string(10) "ID Located"
  }
}
```

What is the core behavior that causes this and how can I remove them without string manipulation?

**Comment by staabm** [comment]
Why do you want to remove it? Those {} identify the global namespace

**Comment by mcred** [comment]
The array that is being generated is being passed to another service and this service does not need the global namespace. The application has one service provider (JSON) and we're switching to another service provider (XML), so the application already expects a certain Key=>Val set up, the {} won't work outside of the scope of the XML wrapper.

**Comment by staabm** [comment]
Is "Stripping the XML namespaces" on http://sabre.io/xml/reading/ what you are after

**Comment by mcred** [comment]
That is what I was looking for. I fixed it with this:

```php
        $this->xml->elementMap = [
            'response' => function (\Sabre\Xml\Reader $reader) {
                return \Sabre\Xml\Deserializer\keyValue($reader, '');
            },
            'summary-result'=> function (\Sabre\Xml\Reader $reader) {
                return \Sabre\Xml\Deserializer\keyValue($reader, '');
            },
            'results' => function (\Sabre\Xml\Reader $reader) {
                return \Sabre\Xml\Deserializer\keyValue($reader, '');
            }
        ];
```

I had tried to remove the namespace before but was trying to pass {} to the keyValue method instead of ''. Once I remove the empty string instead of the curly braces it worked. 

Thank you!
