### ISSUE TITLE
php version colision in 1.5.0 tag

### ISSUE THREAD

**Issue by k33nice** [fruux/sabre-xml#115]
In 1.5.0 tag (major under 2.0.0) specified php>=5.5.5, but it depends on sabre/uri with version gap >=1.0,<3.0.0. sabre/uri version >2.0.0 depends on php>7. Thus, if i try install sabre/xml<2.0.0 with php < 7, it's fails with not satisfy requirement.

**Comment by evert** [comment]
No when you install it on PHP 5.x it will automatically install sabre/uri 1.x. if this is wrong l, please produce proof.
