### ISSUE TITLE
Ability to add an Namespace without a prefix

### ISSUE THREAD

**Issue by tkuijer** [fruux/sabre-xml#120]
I'm trying to generate the following XML:
```xml
<?xml version="1.0"?>
<entry xmlns="http://www.w3.org/2005/Atom">
    <content>...</content>
</entry>
```
However it doesn't seem to be possible to generate an XML element that has a `xmlns` attribute without the prefix.

I'm using the following code:
```php
use Sabre\Xml\Service as SabreXmlService;
$service = new SabreXmlService();
$xml = $service->write('entry', ['content' => '...']);
```

I tried
```php
$xml = $service->write('{http://www.w3.org/2005/Atom}entry', ['content' => '...']);
```
Which results in
```xml
<x1:entry xmlns:x1="http://www.w3.org/2005/Atom">
    <content>...</content>
</x1:entry>
```

**Comment by evert** [comment]
Hi @tkuijer,

This is correct:

    $xml = $service->write('{http://www.w3.org/2005/Atom}entry', ['content' => '...']);

You just need to set the prefix to an empty one:

    $server->namespaceMap['{http://www.w3.org/2005/Atom}entry'] = '';
