### ISSUE TITLE
PHP Version Break

### ISSUE THREAD

**Issue by TheGIBSON** [fruux/sabre-xml#123]
If i use php version 5.6.*, i have to select xml package version 1.5.0.
and it's ok, but package also requires sabre/uri latest version that only supports php version 7 or more.

**Comment by evert** [comment]
If you run composer on PHP 5.6, the correct package will be selected. This problem only occurs if you run composer on PHP 7.

If you don't like this, you can specify a specific sabre/uri package version in your own composer.json
