### ISSUE TITLE
readerMap when element exists on multiple levels

### ISSUE THREAD

**Issue by niektenhoopen** [fruux/sabre-xml#127]
I am currently working on processing a XML file of a third party and am stuck on handling node with an identical name, but on multiple levels. For example:

```
<products>
  <product>
    <name>Test</name>
    <deeplinks>
      <product>http://link-to-product</product>
      <documentation>http://link-to-documentation</documentation>
      <warranty>http://link-to-warranty</documentation>
    </deeplinks>
  </product>
</products>
```

The result I am looking for, looks like this:
```
$products = [
  [0] => Product object {
      'name' => 'Test',
      'deeplinks' => [
        'product' => 'http://link-to-product'
        ...
      ]
  ...
  }
]
```

But I cannot figure out how to fix this with sabre-xml. The problem is that the Product-node exists on multiple levels, once for products->product and once for products->product->deeplinks->product. 

```
'{}Product' => function(Reader $reader) { }
```

works on both different types Product-nodes. Is there a way to distinguish between the two different types of Product-nodes within the sabre-xml library?

**Comment by staabm** [comment]
Both elements are defined within the same namespace?

If so, I dont think this is valid xml...?

**Comment by evert** [comment]
Hi! It definitely is valid XML. Elements' definition can depend on context.

There's a built in feature to deal with this exact thing. I'm on mobile, so I'll be a bit short.

Inside your deseializer function you can call:

    $reader->pushContext()

At that point you can override things in

    $reader->elementMap

And when you hit the bottom of your reader function call

    $reader->popContext

A few reader functions also just support passing the elementMap which becomes the context for the entire subtree.

Let me know if you have more questions. Can go deeper once I'm at a laptop again.

**Comment by niektenhoopen** [comment]
@evert Now I'm suffering from the "deer in the headlight" syndrome. I've been looking into the documentation/code the last hour but I have literally no idea where to start. Are there any examples of usage of this function? I could not find any. I would be happy with bringing pie to Fruux HQ in exchange for help though.

**Comment by evert** [comment]
Hi @niektenhoopen ,

Here's an example. I don't know for certain if this makes the most sense for you. My assumption is that _any_ element in deepLinks is just a single key->value element with urls and things don't appear more than once.

This is how I would define the deserializer for `deeplinks` and I'm assuming a `http://example.org/` namespace.

```php
$server->elementMap['{http://example.org/}deeplinks'] = function(Sabre\Xml\Reader $reader) {
   // Create a new parsing context.
   $reader->pushContext();

   // Override the elementMap for this sub-tree. In this case we don't want _any_ custom parsers.
   $reader->elementMap = [];

   // Parse sub-elements
   $result = \Sabre\Xml\Deserializer\keyValue($reader, 'http://example.org');

   // Restore original parsing context.
   $reader->popContext();

   return $result;
};
```

Hope this makes sense!

**Comment by niektenhoopen** [comment]
Yes, I should be able to make that work! Thank you, @evert!
