### ISSUE TITLE
Integrating prefix-notation

### ISSUE THREAD

**Issue by evert** [fruux/sabre-xml#17]
Lets face it, people hate clark notation.

We should add the ability for people to register and use prefixes during reading and writing. The prefixes used during reading are independent of the actual declared prefixes in the xml document, so it basically behaves similarly to `registerXPathNamespace` in simplexml.

Example

```php
$writer->namespaceMap = [
   'd' => 'DAV:',
];

$writer->write('d:foo', 'bar');

/// Instead of:

$writer->write('{DAV:}foo', 'bar');
```

The change in the preceding example may seem minimal, but most namespace declarations are not 4 characters, they are massive urls.

It's a bit of a different story with reading though, as for writing, we can easily support both syntaxes unambiguously at the same time:

```php
$writer->write('d:foo', 'bar');
$writer->write('{DAV:}foo', 'bar');
``` 

During reading though, a choice needs to be made. Or can we make it optional?

**Comment by padraic** [comment]
This was pretty much the very first thing I started looking for. I have urls here that would be quite long comparatively. There's also the matter of memorising such long strings for documents where multiple namespaces feature (even Atom have quite a variety).

**Comment by evert** [comment]
@padraic i can see it's a bit frustrating, but frankly I'm not 100% certain on how to correctly solve it.

The biggest issue is that by using a 'global configuration' for namespace to prefix mapping, it means that the individual element classes need to either use the global configuration to figure out the correct prefixes for their namespace (pretty much defeating the purpose).

Or: we just have to assume that users such as yourself simply always want to map namespaces, and don't care much for re-using the parser classes in other projects (or force the other projects to re-use the same prefixes).

Most of this only applies to _reading_ though. For writing it's a bit easier, because you can actually just use prefixes in all of the function names.

So I'm basically not necessarily against the idea, but I'm stumped as to how to do this well.

**Comment by DaanBiesterbos** [comment]
I feel like using namespaces is what you need. You can omit the xmlns declaration if you want to, and use it only for markup but I think that should be optional. To use the prefix and omit the namespace you can just pass null.  

There is an example in the documentation.
http://php.net/manual/en/function.xmlwriter-start-element-ns.php

**Comment by evert** [comment]
Closing this ticket. If more specific features are proposed in the future I'll definitely consider it, but this never really went anywhere.
