### ISSUE TITLE
How to parse…

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-xml#32]
… this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<vcards xmlns="urn:ietf:params:xml:ns:vcard-4.0">
 <vcard>
  <ext:my-prop ext:xmlns="http://example.com/extensions/my-vcard">
   <parameters>
    <pref><integer>1</integer></pref>
   </parameters>
   <text>value goes here</text>
  </ext:my-prop>
 </vcard>
</vcards>
```
because I have `Sabre\Xml\LibXMLException: Namespace prefix ext for xmlns on my-prop is not defined
 on line 4, column 25`. The problem is I don't declare `ext` because I don't know it exists.

**Comment by evert** [comment]
The correct syntax is:

    <ext:my-prop xmlns:ext="http://example.com/extensions/my-vcard">

**Comment by evert** [comment]
I wanted to add to this though, that I don't think it's a big deal if we don't support properties in alternative namespaces (the XML property) just yet... we can leave this as a future todo...

**Comment by evert** [comment]
However, if you do want to implement this... I imagine you really want to use [Sabre\Xml\Element\XmlFrament](https://github.com/fruux/sabre-xml/blob/master/lib/Element/XmlFragment.php)

**Comment by Hywan** [comment]
Thanks.
