### ISSUE TITLE
Make it easier to specify built-in deserializers in the elementMap 

### ISSUE THREAD

**Issue by evert** [fruux/sabre-xml#36]
Right now we need to do something like this for a KeyValue:

    $reader->elementMap['someelementname'] = 'Sabre\\Xml\\Element\\KeyValue';

With PHP 5.5 we can at least do this:

    $reader->elementMap['someelementname'] = KeyValue::name;

But it still requires an import. I wonder if there's a way we could just do this:

    $reader->elementMap['someelementname'] = KEYVALUE;

But I don't even know if we can import constants.

**Comment by Hywan** [comment]
```php
namespace foo { const BAR = 'baz'; }
namespace { var_dump(foo\BAR); /* string(3) "baz" */ }
```
