### ISSUE TITLE
Serializable multiple children

### ISSUE THREAD

**Issue by russellgalpin** [fruux/sabre-xml#46]
Is there a way to Serialize multiple children?

By way of an example, if I wanted to create the following XML document:

```xml
<entity>
	<childentity attr1=“attr1” attr2=“attr2” />
	<childentity attr1=“attr1” attr2=“attr2” />
</entity>
```
In theory, I should be able to do the following?

```php
<?php

class ChildEntity implements \Sabre\Xml\XmlSerializable
{
	function xmlSerialize(\Sabre\Xml\Writer $writer)
	{
		$writer->write([
			[
				'name' => 'childentity',
				'attributes' => ['attr1' => 'attr1', 'attr2' => 'attr2'],
				'value' => ''
			]
			
		]);
	}
}

$writer = new \Sabre\Xml\Writer();
$writer->openMemory();
$writer->startElement('entity');
$writer->write([
	new ChildEntity(),
	new ChildEntity()
]);
$write->endElement();
echo $writer->outputMemory();
```

But this fails with the error:

>When passing an array to ->write with numeric indices, every item must be an array containing the "name" and "value" key

**Comment by evert** [comment]
Hi @russellgalpin. The _recommended_ way to do this, is for your `ChildEntity` class to _not_ write it's own element name. Xml serializers/deserializers _should_ only read/write it's element value (attributes, text-content, child-elements) but not the element name itself.

So I would personally rewrite your example in this way:

```xml
<entity>
	<childentity attr1=“attr1” attr2=“attr2” />
	<childentity attr1=“attr1” attr2=“attr2” />
</entity>
```
In theory, I should be able to do the following?

```php
<?php

include 'vendor/autoload.php';

class ChildEntity implements \Sabre\Xml\XmlSerializable
{
    function xmlSerialize(\Sabre\Xml\Writer $writer)
    {
        $writer->writeAttributes([
            'attr1' => 'attr1',
            'attr2' => 'attr2'
        ]);
    }
}

$writer = new \Sabre\Xml\Writer();
$writer->openMemory();
$writer->writeElement('entity', [
    [
        'name' => 'childentity',
        'value' => new ChildEntity()
    ],
    [
        'name' => 'childentity',
        'value' => new ChildEntity()
    ],
]);
echo $writer->outputMemory();
```

However, if you don't like that and you want to keep your current structure, you can just replace:

```php
$writer->write([
	new ChildEntity(),
	new ChildEntity()
]);
```

with:

```php
$writer->write(new ChildEntity());
$writer->write(new ChildEntity());
```

**Comment by judgej** [comment]
Would this not work in the original form if the `childEntity()` were able to serialise into the long form for an element? Hitting this issue myself, an array like this allows multiple submling elements of the same name:

~~~xml
                    'details' => [
                        [
                            'name' => 'detail',
                            'attributes' => [
                                'ID' => '1',
                            ],
                            'value' => '',
                        ],
                        [
                            'name' => 'detail',
                            'attributes' => [
                                'ID' => '2',
                            ],
                            'value' => '',
                        ],
                    ],
~~~

which gives this output:

~~~xml
<details>
    <detail ID="1"></detail>
    <detail ID="2"></detail>
</details>
~~~

I suspect the original issue, right at the top, is an extra level of `[]` included in the `$writer->write()`. Take out that initial wrapping `[]` it it may just work:

~~~php
        $writer->write([
            'name' => 'childentity',
            'attributes' => ['attr1' => 'attr1', 'attr2' => 'attr2'],
            'value' => ''
        ]);
~~~

**Comment by evert** [comment]
Yes probably =) and while I don't think `attributes` is ever required, `value` was but we're fixing that in version 1.3 (already on master)

**Comment by judgej** [comment]
Here is another approach: you can dive down into the `entity` element and write out multiple `childEntity` elements in that, then close the `entity` element. When you open an element, all `$writer->write()` calls write into that element.

For example, here is my `Order` serializer method, which takes a list of `detail` elements (the order line) and renders them into a single `details` element.

~~~php
    function xmlSerialize(Writer $writer)
    {
        // Some elements at the order level.
        $writer->write([
            'customerref' => $this->getCustomerRef(),
            'shippingMethod' => $this->shippingMethod,
        ]);

        // The collection of order lines.
        $writer->startElement('details');

        // Write each order line.
        foreach($this->orderLines as $orderLine) {
            $writer->write([
                'detail' => $orderLine
            ]);
        }

        $writer->endElement();
    }
~~~

Just in case it's useful...
