### ISSUE TITLE
Fatal error: Uncaught exception 'Sabre\Xml\LibXMLException' with message 'Extra content at the end of the document on line 42, column 1'

### ISSUE THREAD

**Issue by Nicero** [fruux/sabre-xml#50]
I tried you very basic example with my XML:
```
$xml = simplexml_load_file('myxml.xml');

$reader = new Sabre\Xml\Reader();
$reader->xml($xml);
print_r($reader->parse());
```
and got: 

```
Fatal error: Uncaught exception 'Sabre\Xml\LibXMLException' with message 'Extra content at the end of the document on line 42, column 1'
```

I then tried the same very basic example using your XML and got the same error (I'm using PHP 5.4.21).

**Comment by Nicero** [comment]
Solved by loading file like this:
```
$xml = file_get_contents('myxml.xml');
```

**Comment by evert** [comment]
or better yet, use the `open()` method instead of `xml()` to load it from disk in a streaming fashing. Not sure where you got simplexml_load_file from though =)
