### ISSUE TITLE
Uncaught exception 'Sabre\Xml\LibXMLException' with message 'Entity 'euml'

### ISSUE THREAD

**Issue by rolandow** [fruux/sabre-xml#56]
I think I have some weird, unvalid RSS feed. It has data in xml tags that is encoded with htmlentities. How can I properly decode this?

Example rss feed: http://www.punt.nl/?rss

**Comment by evert** [comment]
Ah yea, that is pretty terrible. Are you not able to fix the source?

The best way to solve this might be a str_replace. I think you should also be able to actually import the HTML DTD entries to import these entities, but not sure I'd recommend that.

http://stackoverflow.com/questions/6508860/how-do-i-define-html-entity-references-inside-a-valid-xml-document
