### ISSUE TITLE
Returning null from a deserializer

### ISSUE THREAD

**Issue by staabm** [fruux/sabre-xml#78]
Today I ran into a issue because I forgot to return a value from my deserializer callable.

Is there a valid use-case to `return null` from a deserilizer or could we improve DX by throwing a `Exception` with a proper message when a deserilizer doesnt return anything aka returns `null´?

In case someone defines a deserilizer method, shouldnt it be obligatory to return a proper deserialized value?

**Comment by evert** [comment]
I'm actually returning `null` in a number of cases in sabre/dav code, so in my case I would say: yes I think there's cases where this might be useful. In some cases I just want to be able to respresent "there was no value".

Your unittests should ideally just catch this... I have wondered if we can make the testing experience a bit better
