### ISSUE TITLE
Documentation typos for `Sabre\Xml\Deserializer` namespace

### ISSUE THREAD

**Issue by darraghenright** [fruux/sabre-xml#86]
Hi there

Love the library - great work!

Apologies if this is not the right place to report a possible documentation bug, but I am writing some code that reads XML, and I just upgraded to 1.3 in order to use `Sabre\Xml\Deserializers\keyValue`, as it's specified in the [Reading XML docs](http://sabre.io/xml/reading/).

However, I got an `undefined function` error. A quick look at the library showed me that the namespace is actually `Sabre\Xml\Deserializer`, which works fine.

Based on a page search there are about a dozen instances of `Deserializers` in the code examples on that page. I assume I am looking at the correct documentation version - apologies if not!

Thanks again,
Darragh

**Comment by evert** [comment]
Hi @darraghenright . Thanks for the report, indeed a documentation mistake.

For future reference, you can actually make edits yourself here:

https://github.com/fruux/sabre.io/blob/master/source/xml/reading.md

**Comment by darraghenright** [comment]
Hi. I'd be glad to make those edits if you haven't already. I figured it
might be possible but it wasn't immediately obvious to me :)

**Comment by evert** [comment]
I just made the edits actually, but I appreciate the offer!
