### ISSUE TITLE
Silence operator on read

### ISSUE THREAD

**Issue by GDmac** [fruux/sabre-xml#88]
Is the silence operator still needed?
(also the one mentioned in #87 )
https://github.com/fruux/sabre-xml/blob/master/lib/Reader.php#L65
https://github.com/fruux/sabre-xml/blob/master/lib/Reader.php#L145

It seems the issue/bug has been fixed
https://bugs.php.net/bug.php?id=64230

Testing your example code from that bug report
does not throw errors here (php 5.6.14)

**Comment by evert** [comment]
If it's fixed in the minimum supported PHP version then I agree that it can be removed. Currently the minimum version is 5.4.1. I would be willing to increase the revision number as the minimum version, if the bug is fixed somewhere in 5.4.x. Any idea if it was?

**Comment by GDmac** [comment]
i have no idea, and can not deduce it from the bug report either.

**Comment by evert** [comment]
Here's the github commit:

https://github.com/php/php-src/commit/dc3d360a0ff8c17cb2ce2030813d30b578249be9

Tags: 5.4.22, 5.5.5, 5.6.0. A two-year old release.. I think I can be ok with increasing the minimum versions to those in the next minor version (1.5.0).

**Comment by evert** [comment]
Unfortunately we recently found out that this was still needed to support hhvm, which emits errors regardless of this setting.

So I'm reverting this until it's also fixed in hhvm.
