### ISSUE TITLE
pass a XSD path via xml:schemaLocation

### ISSUE THREAD

**Issue by staabm** [fruux/sabre-xml#93]
using the `namespaceMap` I can define xml-namespaces which get written into the root element of the generated xml.

After adding a `xsi` schema namespace into the map via 
`$namespaces['http://www.w3.org/2001/XMLSchema-instance'] = 'xsi';`
how can I make the writer produce a `xsi:schemaLocation` location attribute?

I need a xml like 
```xml
<root-element 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://myns/1 https://host/path/to/my/schema.xsd"
  xmlns:x1="http://myns/1"
  xmlns:x2="http://myns/2"
...
```

**Comment by staabm** [comment]
I am not sure whether this question is generic enough to be handled outside of a custom object serializer (since the attribute is more technology based then problem-domain based) or if I should have a custom serializer which adds this attribute like it adds all the domain specific properties.

**Comment by evert** [comment]
You can use:

```php
$writer->writeAttribute(
    '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation',
    'http://myns/1 https://host/path/to/my/schema.xsd'
 );
```

**Comment by newbro** [comment]
What if I were to use service class instead of writer? could i accomplish the same?

**Comment by rico** [comment]
sorry to pick that up again - but how exactly should that work? I get the `xmlns:xsi, but need an additional `xsi:schemaLocation`. I tried to apply the code in the last comment:

    $writer = $this->service->getWriter();
    $writer->openMemory();
    $writer->setIndent(true);
    $writer->startDocument('1.0', 'UTF-8', 'no');

    $writer->writeAttribute(
        '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation',
        'http://www.forum-datenaustausch.ch/invoice generalInvoiceRequest_440.xsd'
    );

    $writer->writeElement($this->ns . 'request', '');

    return $writer->outputMemory();

... but nothing changes. Can you clarify?

**Comment by evert** [comment]
@rico, you can only write an attribute _after_ you wrote the opening xml tag. So if you reverse your `writeElement` and `writeAttribute` statements, it should in theory work.

**Comment by rico** [comment]
@evert - thanks for answering. However, that did not work for me. I ended up doing it like this:

	$this->writer->startElement($this->ns('request'));
	$this->writer->writeAttribute('{http://www.w3.org/2001/XMLSchema-instance}schemaLocation', $namespace . ' ' . $xsd);
	$this->writer->write($content);
	$this->writer->endElement();

- that works. 

btw. fantastic work on your side. Love this package.

**Comment by evert** [comment]
Thanks! And yea sorry, I had missed that you use `writeElement` instead of `startElement`.
