### ISSUE TITLE
simpletypes and restrictions

### ISSUE THREAD

**Issue by staabm** [fruux/sabre-xml#95]
since schemas get more complex we also experience simpletypes which define further restrictions, e.g.

```xml
...
    <xs:simpleType name="sysTableCodeKey">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
...
```

those types are expected to be handled similar to other `xs:string`s, e.g.
```xml 
<xs:element name="request_id" type="xs:string"/>
<!-- vs. -->
<xs:element name="sys-key" type="my-types:sysTableCodeKey"/>
```

unfortunately the valueobject mapping we use atm does not recognize those string-types.
I am not sure how I need to configure the reader so he picks this values up like a regular `xs:string`

atm I have xml messages which contain information for those simple-type'd columns but after parsing those into php objects no value is left. all the properties stay `null` (because its the default in a php class when a property is declared but no value assigned later on).

**Comment by staabm** [comment]
It feels like its more like a XmlReader issue then a sabre-xml one. the XmlReader api is kind of alien to me and I dont know really how to handle it in such cases.

**Comment by staabm** [comment]
While digging thru the code I realized that this problem can be solved on the de/serializer level.
Do you think it makes sense to have this kind of feature in sabre-xml or do you consider it more a edge case within my app?

**Comment by evert** [comment]
I guess I don't really understand the issue here :/ I don't do a lot with XSD. Could you elaborate further, maybe with an example?

**Comment by staabm** [comment]
the fix for https://github.com/fruux/sabre-xml/issues/97#issuecomment-219784692 also fixed this for me.
