### ISSUE TITLE
how to generate multiple same name nodes?

### ISSUE THREAD

**Issue by eddy8** [fruux/sabre-xml#98]
like this:
```
<books>

    <book>...</book>

    <book>...</book>

    <book>...</book>

</books>
```
thanks:)

**Comment by staabm** [comment]
see e.g. http://sabre.io/xml/

just invoke `service->write()` several times

**Comment by eddy8** [comment]
can you show some code for me? I

**Comment by evert** [comment]
If you can share what code you already have, I can show you how to modify it to make this work.

**Comment by eddy8** [comment]
```
$service = new Sabre\Xml\Service();
        $xmlstr = $service->write('books', [
                'book' =>  'php',
                'book1' =>  'c++',
                'book2' =>  'c#',
            ]);
echo $xmlstr;
```
this will output:
```
<?xml version="1.0"?>
<books>
 <book>php</book>
 <book1>c++</book1>
 <book2>c#</book2>
</books>
```
i want the child nodes of books have same name. but php's array does not support same name key, so ?@evert

**Comment by evert** [comment]
Thanks, great sample. Here's one solution:

```php
$service = new Sabre\Xml\Service();
$xmlstr = $service->write('books', [
    ['name' => 'book', 'value' => 'php'],
    ['name' => 'book', 'value' => 'c++'],
    ['name' => 'book', 'value' => 'c#'],
]);
echo $xmlstr;
```

We call this type of structure a 'repeating element'. It's pretty common in xml formats, so we also have a serializer function for this:


```php
$service = new Sabre\Xml\Service();
$books = [
   'php',
   'c++',
   'c#',
];

$xmlstr = $service->write('books', function($writer) use ($books) {
    Sabre\Xml\Serializer\repeatingElements($writer, $books, 'book');
});
```

Lastly, if you don't like the serializer function you can also do this manually instead:

```php
$service = new Sabre\Xml\Service();

$xmlstr = $service->write('books', function($writer) use ($books) {
    $writer->writeElement('book','php');
    $writer->writeElement('book','c++');
    $writer->writeElement('book','c#');
});
```

**Comment by eddy8** [comment]
@evert Thanks. your solution is simple and great. I hope this content can be added to documentation. because i read the document carefully, but found no solution.

**Comment by evert** [comment]
I need to integrate this stuff in the docs for sure. But in the meantime I also turned this issue into a blog post: https://evertpot.com/sabre-xml-repeating-elements/

Hope you don't mind I used you as an example :)

**Comment by jakubkratina** [comment]
Hi guys, 

just found this issue.

I want to mention, according to the code, there is no support for callback as a second parameter.

The code:
```
function write($value) {

        Serializer\standardSerializer($this, $value);

    }
```

However, the snippet with the nested array works, thank you :)
